[package]
name = "spkg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.195"
serde_yaml = "0.9.30"
lazy_static = "1.4.0"
stblib = "0.3.2"